curl -X POST -H "Content-Type: application/json" -d '{
    "nom": "Histoire",
    "description": "Cours dhistoire sur la seconde guerre mondiale",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxNTQ3MTU5MiwiZXhwIjoxNzE1NDc1MTkyfQ._Qcz67jKI238ciyDKGjeIGtqT22bYXsE-ohqg7v84_k"
}'
http://localhost:3000/addMatiere
